version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ./artifacts:/artifacts
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
  
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file:
      - .env
    depends_on:
      - app
    restart: always
